language: python
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+$/"
matrix:
  fast_finish: true
  include:
  - os: linux
    name: Linux
    dist: bionic
    python:
    - 3.6
    - 3.7
    before_install:
      python3 --version;
      pip3 --version;
    env:
    - BUILD_TARGET=linux
    - PYTHON_BIN=python3
    addons:
      apt:
        packages:
        - patchelf
  - os: osx
    name: macOS
    osx_image: xcode11.2
    language: shell # python not working
    before_install:
      python3 --version;
      pip3 --version;
    env:
    - BUILD_TARGET=macos
    - PYTHON_BIN=python3
  - os: windows
    language: shell # python not supported yet
    name: windows64
    before_install:
      choco install python3 --version=3.7.5;
      python -m pip install --upgrade pip;
      python --version;
      pip3 --version;
    env:
    - BUILD_TARGET=windows64
    - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - PYTHON_BIN=python
  - os: windows
    language: shell # python not supported yet
    name: windows32
    before_install:
      choco install python3 --forcex86 --version=3.7.5;
      python -m pip install --upgrade pip;
      python --version;
      pip3 --version;
    env:
    - BUILD_TARGET=windows32
    - PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - PYTHON_BIN=python
install:
- set -e
- pip3 install -r requirements.txt -r requirements-dev.txt
- pip3 install auditwheel twine
- if [[ "${BUILD_TARGET}" = "macos" ]]; then
    pip3 install delocate;
  fi
script:
- set -e
- $PYTHON_BIN setup.py bdist_wheel
- if [[ "${BUILD_TARGET}" = "linux" ]]; then
    auditwheel repair --plat manylinux2010_x86_64 dist/*.whl;
  fi
- if [[ "${BUILD_TARGET}" = "macos" ]]; then
    delocate-wheel -w wheelhouse -v dist/*.whl;
    ls wheelhouse/*any.whl | sed -e 'p;s/any/macosx_10_9_x86_64/' | xargs -n2 mv;
  fi
- if [[ "${BUILD_TARGET}" = "windows64" ]]; then
    mkdir wheelhouse;
    ls dist/*any.whl | sed -e 'p;s/any/win_amd64/' | xargs -n2 cp;
    mv dist/*win_amd64.whl wheelhouse/;
  fi
- if [[ "${BUILD_TARGET}" = "windows32" ]]; then
    mkdir wheelhouse;
    ls dist/*any.whl | sed -e 'p;s/any/win32/' | xargs -n2 cp;
    mv dist/*win32.whl wheelhouse/;
  fi
- if [[ ! -z "${TRAVIS_TAG}" ]]; then
    echo "Deploying to PyPi";
    TWINE_NON_INTERACTIVE=1 twine upload wheelhouse/*.whl;
  else
    echo "Not deploying without git tag.";
  fi
env:
  global:
  - secure: cpJLKiOqUTYB1ozkVus4SlPBP/XJ1uUxfMKos+XLWxEVOTguLIW+bKhLfquY9+PlY2rajl5jxxzrX5RZOgZR0fbHHh9FAzioWhzEEUQb76IKnDD7St8J6Pq65bO1Vk8o0sdtQ+ht8+RK54TJL6d8jxVh4RNV3txBB6wFzkFcw5WTDxgWr/+HsYfC9IQkIXGf8NJmvdCUBunL2xDULZ3rlPzEG/YmXjR79g51juNWvZjDKFjLmpHe/qN8VSws1QrI7tKtTtNrNutlAVnOWSlcnJspzex0WfG4EINyjJH7WQZppLiax55jWSBAzxee3/7jXyDVDOJBPl8JT/GyqoQL/qHDmiJuHm53Ktpgg0saGlcSuYuA643PVVJ2Q1SerTtboukJIfNi08GykSPLIbT6PHqhB7NzaA+rWXWgTIoMUyPQ38M+/2lpVqNc6fwAClAbYrJKxyiH7g6GLShV5/UOqDWK18OGGYnpWs+X2eFPXFXLVfZ540VvqlZimwMd6PZuB6RpgKBcBPH1FMac1dE0+FaNHHHj9KNONkiTfzJCFEThwTtS0z3xrKzq8q8iAmbbhTKMJjwID0hpdKdfvzxkPW7IJiW/zG5X2WBL5gB2bhKhpkiozZCuO087aPxPx6Y+Jua5nt3hm3p1tVqZD3hX+SNv4ymHXfsyeIvweLKi0QQ=
  - secure: CiOtzgly9Rl0KwaA3W3FJTzSaUoSpRVPgSRj+x9UdmDBKHm9dvW3kc5amsUKzx7jF9qb2Cuyw2Bg9kmq7SIIqvvN14/3NkzTb2aDpE+f/O627asKJlrr5CuQtmwFX//ZjLIeLFPySBj/Oz1SUz39hqtRVkyTAPfvxiVu52AQveXqyxhcgC5ALI/kIAVaWeKBqH8f6PJ5HUphL2u+QOO1/r88tEumbmVUA6tvQZxHUsu7tU1SOwB4SAfCwTfwJ8h0ZUEicuTkUB3KJc6gDWF8i2AUi1akrysAO4DDd606K1APA7QusTq+PP16tG23ul6kmme8SNRXZUouqGv902giif3TZdJqSyoPkih4TTUUeQ47xBQ81EJba5lXbEZIu4N3Soxl6RSa6O85LNuc9XKxNSEbruRWROxg+hMBh+8403S4NlWfxnri4SwM8iM98psWjTGyl/JLLNU7JJniiuBY5coEV65XzP/6gnAdo1TGy3kdolnTeocT1Nrx0WSH8LxZM6LhWdt2uV1eJK4NT2MhxW8CI/S6BGiwZV/31+HfMUoseEjYPPaGFDazIWtC6WWlPRFLsk1cktNjK+/KxDThkVBW+kkiGrqifRi8u+TNjWLRJbotNnDq5RYipvXjCIurl1UlPIDx6l7JnJjknblu35JjjOevOn/WDIJdpDTODdw=
