name: Check and PyPi Upload

on:
  push:
    branches:
    - 'main'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  ubuntu24:
    name: Ubuntu 24.04 x86_64
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          tags: true
          fetch-depth: 0

      - name: Install pip and pipx
        run: sudo apt-get install -y python3-pip pipx

      - name: Check style
        run: |
          pipx run ruff format --check --line-length=100 examples
          pipx run ruff check --select=ASYNC,RUF006,E,F --line-length=100 examples
          pipx run ruff check --select=PERF --line-length=100 .
          pipx run codespell .

      - name: Install prerequisites
        run: |
          python3 -m pip install -r requirements.txt -r requirements-dev.txt -r requirements-docs.txt
          python3 -m pip install auditwheel twine

      - name: Create wheel
        run: |
          python3 setup.py bdist_wheel
          mkdir wheelhouse
          export PATH=$PATH:$HOME/.local/bin
          auditwheel repair --plat manylinux2014_x86_64 dist/*.whl

      - name: Check the artifacts
        run: |
          ls -lh "wheelhouse/"

      - name: Create docs
        run: |
          export PATH=$PATH:$HOME/.local/bin
          make -C mavsdk html

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_NON_INTERACTIVE: 1
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export PATH=$PATH:$HOME/.local/bin
          twine upload wheelhouse/*.whl

      - name: Upload docs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export PATH=$PATH:$HOME/.local/bin
          other/tools/upload_docs.sh



  ubuntu24-other:
    name: Ubuntu 24.04 ${{ matrix.arch }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - arch: armv6l
            pypi_arch: linux_armv6l
          - arch: armv7l
            pypi_arch: linux_armv7l
          - arch: aarch64
            pypi_arch: manylinux2014_aarch64

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          tags: true
          fetch-depth: 0

      - name: Install pip
        run: sudo apt-get install -y python3-pip

      - name: Install prerequisites
        run: |
          python3 -m pip install -r requirements.txt -r requirements-dev.txt
          python3 -m pip install twine

      - name: Create wheel
        run: |
          export MAVSDK_SERVER_ARCH=${{ matrix.arch }}
          python3 setup.py bdist_wheel
          ls dist/*any.whl | sed -e 'p;s/any/${{ matrix.pypi_arch }}/' | xargs -n2 mv

      - name: Check the artifacts
        run: |
          ls -lh "dist/"

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_NON_INTERACTIVE: 1
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export PATH=$PATH:$HOME/.local/bin
          twine upload dist/*.whl

  macOS:
    name: macOS ${{ matrix.arch }}
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        include:
          - arch: x64
            wheel_arch: 13_0_x86_64
            runs_on: macos-15-intel
          - arch: arm64
            wheel_arch: 14_0_arm64
            runs_on: macos-15
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          tags: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install prerequisites
        run: |
          python -m pip install -r requirements.txt
          python -m pip install setuptools twine wheel
          python -m pip install --user delocate

      - name: Create wheel
        run: |
          python setup.py bdist_wheel
          export PATH="$(python -m site --user-base)/bin:$PATH"
          delocate-wheel -w wheelhouse -v dist/*.whl
          ls wheelhouse/*any.whl | sed -e 'p;s/any/macosx_${{ matrix.wheel_arch }}/' | xargs -n2 mv

      - name: Check the artifacts
        run: |
          ls -lh "wheelhouse/"

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_NON_INTERACTIVE: 1
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          export PATH=$PATH:$HOME/.local/bin
          twine upload wheelhouse/*.whl

  Windows:
    name: Windows (${{ matrix.arch }})
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - arch: x86
            host_arch: x64
            wheel_arch: win32
          - arch: x64
            host_arch: x64
            wheel_arch: win_amd64
          - arch: arm64
            host_arch: x64
            wheel_arch: win_arm64

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          tags: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          architecture: ${{ matrix.host_arch }}

      - name: Install prerequisites
        run: |
          python3 -m pip install -r requirements.txt -r requirements-dev.txt
          python3 -m pip install twine wheel

      - name: Create wheel
        run: |
          set MAVSDK_SERVER_ARCH=${{ matrix.arch }}
          python3 setup.py bdist_wheel
          Dir "dist/" | rename-item -NewName {$_.name -replace '-any.whl','-${{ matrix.wheel_arch }}.whl'}

      - name: Check the artifacts
        run: |
          ls "dist/"

      - name: Upload to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_NON_INTERACTIVE: 1
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          twine upload dist/*.whl
